#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cd wingMotion_snappyHexMesh
cleanCase

cd ../wingMotion2D_simpleFoam
rm -rf *[1-9]*
rm -f log.* 2>/dev/null
rm -rf postProcessing
rm -rf processor0
rm -rf constant/polyMesh
#------------------------------------------------------------------------------
