#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory
cd /home/fmg/OpenFOAM/fmg-6/run/Airfoil/cfd_openfoam/
./Allclean
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Make 3D mesh in slab of cells.
cd wingMotion_snappyHexMesh
runApplication blockMesh
runApplication snappyHexMesh -overwrite
#cp log.snappyHexMesh ../../simvalue/CP$1 #
#cp log.blockMesh ../../simvalue/CP$1 #

# Make a 2D mesh by extruding a patch and solve to steady state.
cd ../wingMotion2D_simpleFoam
runApplication extrudeMesh
runApplication createPatch -overwrite

# Running Simulation in parallel, currently with 36 cores on mainframe
runApplication decomposePar #> log.decomposePar
application=$(getApplication)
runApplication mpirun -np 36 $application -parallel > log.simplefoam
mkdir ../../simvalue/CP$1

#For Copying Files
#cp log.mpirun ../../simvalue/CP$1 #
cp postProcessing/forces/0/forces.dat ../../simvalue/CP$1
cp postProcessing/forceCoeffs/0/forceCoeffs.dat ../../simvalue/CP$1
cp postProcessing/residuals/0/residuals.dat ../../simvalue/CP$1

cd ../
./Allclean
#-----------------------------------------------------------------------------#
